name: Build
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17
      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew build -x lint -x test
