name: Check formatting
on:
  pull_request:
  push:
    branches: [main]
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 25
      - run: |
          curl -sSL -o ktfmt.jar https://github.com/facebook/ktfmt/releases/download/v0.59/ktfmt-0.59-with-dependencies.jar
          java -jar ktfmt.jar --dry-run --kotlinlang-style --set-exit-if-changed .
