name: Publish API reference
on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
  pages: write
jobs:
  publish-api-reference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17
      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew dokkaGenerate
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: lib/build/dokka/html/
      - uses: actions/deploy-pages@v4
